CREATE TABLE IF NOT EXISTS "alexander-cannon-personal_comment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "alexander-cannon-personal_comment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"post_id" integer NOT NULL,
	"body" varchar(2048) NOT NULL,
	"name" varchar(256),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "alexander-cannon-personal_contact" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "alexander-cannon-personal_contact_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"email" varchar(256) NOT NULL,
	"name" varchar(256) NOT NULL,
	"company" varchar(256),
	"job_title" varchar(256),
	"message" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "alexander-cannon-personal_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "alexander-cannon-personal_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"body" text,
	"slug" varchar(256),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "alexander-cannon-personal_comment" ADD CONSTRAINT "alexander-cannon-personal_comment_post_id_alexander-cannon-personal_post_id_fk" FOREIGN KEY ("post_id") REFERENCES "public"."alexander-cannon-personal_post"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "post_id_idx" ON "alexander-cannon-personal_comment" USING btree ("post_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "email_idx" ON "alexander-cannon-personal_contact" USING btree ("email");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "name_idx" ON "alexander-cannon-personal_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "slug_idx" ON "alexander-cannon-personal_post" USING btree ("slug");